services:
    odiseo_sylius_avatax_plugin.api.avatax_client:
        class: Odiseo\SyliusAvataxPlugin\Api\AvataxClient
        arguments:
            - '@odiseo_sylius_avatax_plugin.provider.enabled_avatax_configuration'
        lazy: true
