services:
    odiseo_sylius_avatax_plugin.taxation.order_avatax_taxes_applicator:
        class: Odiseo\SyliusAvataxPlugin\Taxation\Applicator\OrderAvataxTaxesApplicator
        arguments:
            - '@odiseo_sylius_avatax_plugin.api.avatax_client'
            - '@sylius.factory.adjustment'
            - '@sylius.provider.channel_based_default_zone_provider'
            - '@sylius.zone_matcher'
            - '@odiseo_sylius_avatax_plugin.provider.enabled_avatax_configuration'
            - '@odiseo_sylius_avatax_plugin.resolver.order_item_avatax_code'
            - '@odiseo_sylius_avatax_plugin.resolver.shipping_avatax_code'

    sylius.taxation.order_items_based_strategy:
        class: Sylius\Bundle\CoreBundle\Taxation\Strategy\TaxCalculationStrategy
        arguments:
            - 'order_items_based'
            - ['@sylius.taxation.order_items_taxes_applicator', '@sylius.taxation.order_shipment_taxes_applicator', '@odiseo_sylius_avatax_plugin.taxation.order_avatax_taxes_applicator']
        tags:
            - { name: sylius.taxation.calculation_strategy, type: order_items_based, label: 'Order items based' }

    sylius.taxation.order_item_units_based_strategy:
        class: Sylius\Bundle\CoreBundle\Taxation\Strategy\TaxCalculationStrategy
        arguments:
            - 'order_item_units_based'
            - ['@sylius.taxation.order_items_taxes_applicator', '@sylius.taxation.order_shipment_taxes_applicator', '@odiseo_sylius_avatax_plugin.taxation.order_avatax_taxes_applicator']
        tags:
            - { name: sylius.taxation.calculation_strategy, type: order_item_units_based, label: 'Order item units based' }
